server:
  port: 8080

spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
       defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    
zuul:
  prefix: /api/v1/movie
  routes:
    starwars-service:
      path: /starwars/**
      serviceId: starwars-service

